### ISSUE TITLE
Potjans_2014 example breaks at GetRecSpikeTimes()

### ISSUE THREAD

**Issue by jhnnsnk** [nest/nest-gpu#31]
The argument of `GetRecSpikeTimes()` appears to be of type `int` but `NodeSeq` is expected:

```
Traceback (most recent call last):
  File "/home/senk/repositories/nest-gpu/python/Potjans_2014/run_microcircuit.py", line 79, in <module>
    net.evaluate(raster_plot_interval, firing_rates_interval)
  File "/home/senk/repositories/nest-gpu/python/Potjans_2014/network.py", line 169, in evaluate
    spike_times = ngpu.GetRecSpikeTimes(population[i_neur])
  File "/home/senk/repositories/nest-gpu/lib/python3.10/site-packages/nestgpu.py", line 2164, in GetRecSpikeTimes
    raise ValueError("First argument type of GetRecSpikeTimes must be NodeSeq")
ValueError: First argument type of GetRecSpikeTimes must be NodeSeq

```

**Comment by gmtiddia** [comment]
I've updated the spike recording function of the Potjans_2014 examples. The related pull request is #32.
